/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OnboardingOrganizationRouteImport } from './routes/onboarding/organization'
import { Route as AppOrganizationIdTicketsRouteImport } from './routes/app/$organizationId/tickets'
import { Route as AppOrganizationIdTicketsIndexRouteImport } from './routes/app/$organizationId/tickets.index'
import { Route as AppOrganizationIdTicketsNewRouteImport } from './routes/app/$organizationId/tickets.new'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OnboardingOrganizationRoute = OnboardingOrganizationRouteImport.update({
  id: '/onboarding/organization',
  path: '/onboarding/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrganizationIdTicketsRoute =
  AppOrganizationIdTicketsRouteImport.update({
    id: '/$organizationId/tickets',
    path: '/$organizationId/tickets',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppOrganizationIdTicketsIndexRoute =
  AppOrganizationIdTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppOrganizationIdTicketsRoute,
  } as any)
const AppOrganizationIdTicketsNewRoute =
  AppOrganizationIdTicketsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AppOrganizationIdTicketsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app/': typeof AppIndexRoute
  '/app/$organizationId/tickets': typeof AppOrganizationIdTicketsRouteWithChildren
  '/app/$organizationId/tickets/new': typeof AppOrganizationIdTicketsNewRoute
  '/app/$organizationId/tickets/': typeof AppOrganizationIdTicketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app': typeof AppIndexRoute
  '/app/$organizationId/tickets/new': typeof AppOrganizationIdTicketsNewRoute
  '/app/$organizationId/tickets': typeof AppOrganizationIdTicketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/onboarding/organization': typeof OnboardingOrganizationRoute
  '/app/': typeof AppIndexRoute
  '/app/$organizationId/tickets': typeof AppOrganizationIdTicketsRouteWithChildren
  '/app/$organizationId/tickets/new': typeof AppOrganizationIdTicketsNewRoute
  '/app/$organizationId/tickets/': typeof AppOrganizationIdTicketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/onboarding/organization'
    | '/app/'
    | '/app/$organizationId/tickets'
    | '/app/$organizationId/tickets/new'
    | '/app/$organizationId/tickets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/onboarding/organization'
    | '/app'
    | '/app/$organizationId/tickets/new'
    | '/app/$organizationId/tickets'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/onboarding/organization'
    | '/app/'
    | '/app/$organizationId/tickets'
    | '/app/$organizationId/tickets/new'
    | '/app/$organizationId/tickets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OnboardingOrganizationRoute: typeof OnboardingOrganizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/onboarding/organization': {
      id: '/onboarding/organization'
      path: '/onboarding/organization'
      fullPath: '/onboarding/organization'
      preLoaderRoute: typeof OnboardingOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$organizationId/tickets': {
      id: '/app/$organizationId/tickets'
      path: '/$organizationId/tickets'
      fullPath: '/app/$organizationId/tickets'
      preLoaderRoute: typeof AppOrganizationIdTicketsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/$organizationId/tickets/': {
      id: '/app/$organizationId/tickets/'
      path: '/'
      fullPath: '/app/$organizationId/tickets/'
      preLoaderRoute: typeof AppOrganizationIdTicketsIndexRouteImport
      parentRoute: typeof AppOrganizationIdTicketsRoute
    }
    '/app/$organizationId/tickets/new': {
      id: '/app/$organizationId/tickets/new'
      path: '/new'
      fullPath: '/app/$organizationId/tickets/new'
      preLoaderRoute: typeof AppOrganizationIdTicketsNewRouteImport
      parentRoute: typeof AppOrganizationIdTicketsRoute
    }
  }
}

interface AppOrganizationIdTicketsRouteChildren {
  AppOrganizationIdTicketsNewRoute: typeof AppOrganizationIdTicketsNewRoute
  AppOrganizationIdTicketsIndexRoute: typeof AppOrganizationIdTicketsIndexRoute
}

const AppOrganizationIdTicketsRouteChildren: AppOrganizationIdTicketsRouteChildren =
  {
    AppOrganizationIdTicketsNewRoute: AppOrganizationIdTicketsNewRoute,
    AppOrganizationIdTicketsIndexRoute: AppOrganizationIdTicketsIndexRoute,
  }

const AppOrganizationIdTicketsRouteWithChildren =
  AppOrganizationIdTicketsRoute._addFileChildren(
    AppOrganizationIdTicketsRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrganizationIdTicketsRoute: typeof AppOrganizationIdTicketsRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrganizationIdTicketsRoute: AppOrganizationIdTicketsRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OnboardingOrganizationRoute: OnboardingOrganizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
